image: docker:git
services:
  - docker:24.0.3-dind
variables:
  DOCKER_TLS_CERTDIR: "/certs"
  TMPDIR: "${CI_PROJECT_DIR}.tmp"
  CCACHE_DIR: ${CI_PROJECT_DIR}/ccache
    
cache:
  key: "${CI_JOB_NAME}" # https://docs.gitlab.com/ee/ci/caching/#sharing-caches-across-different-branches
  paths: 
  - ccache

before_script:
  - apk add --update bash coreutils tar
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master
  # Inject the CI JOB token to allow us to download from our private repos in the .rosinstall file
  # - sed -i 's|https://gitlab.tudelft.nl|https://gitlab-ci-token:'${CI_JOB_TOKEN}'@gitlab.tudelft.nl|g' ${CI_PROJECT_DIR}/.rosinstall
  
foxy:
  script:
    .industrial_ci/gitlab.sh
  variables:
    ROS_DISTRO: foxy
    DOCKER_IMAGE: "ros:foxy"
    DOCKER_RUN_OPTS: '-v /etc/ssl/certs:/etc/ssl/certs:ro'

humble:
  script:
    .industrial_ci/gitlab.sh
  variables:
    ROS_DISTRO: humble
    DOCKER_IMAGE: "ros:humble"
    DOCKER_RUN_OPTS: '-v /etc/ssl/certs:/etc/ssl/certs:ro'
